import React from 'react';

class MainContent extends React.Component {
  render() {
    return (
      <section className="main-content">
        <h1>
          <a id="javascript-fuzzy-set-theory-library" className="anchor" href="#javascript-fuzzy-set-theory-library" aria-hidden="true"><span aria-hidden="true" className="octicon octicon-link"></span></a>Javascript Fuzzy Set Theory library
        </h1>
        <p>Fuzzy set theory utility javascript library</p>
        <p><em>Under construction</em></p>
        <p><img src={'http://i.imgur.com/fI9qT.gif'} width="48" /></p>
        <h2>
          <a id="todo" className="anchor" href="#todo" aria-hidden="true"><span aria-hidden="true" className="octicon octicon-link"></span></a>TODO
        </h2>
        <ul>
            <li>Implement many sorts of MFs and test</li>
        </ul>
        <ul className="js-top-transactions"></ul>
        <footer className="site-footer">
            <span className="site-footer-owner"><a href="https://github.com/leoaretakis/fuzzy-theo">Fuzzy-theo</a> is maintained by <a href="https://github.com/leoaretakis">leoaretakis</a>.</span>
            <span className="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
        </footer>
      </section>
    );
  }
}

export default MainContent;
